package user

import "errors"

// NewUserID creates a user ID
type User struct {
	ID       UserID
	Email    Email
	Password Password
}

// NewUser creates a user
func NewUser(email RawEmail, password RawPassword) (*User, error) {

	// Create a new user ID
	// In a real-world application, this ID should be generated by a database
	id := NewUserID(1)

	e, err := NewEmail(email)
	if err != nil {
		return nil, err
	}

	p := NewPassword(password)

	// Create a new user
	u := User{
		ID:       id,
		Email:    *e,
		Password: p,
	}

	return &u, nil
}

// Delete deletes a user
func (u *User) Delete(actor User) (*DeletableUserID, error) {

	// Check if the actor is the user to be deleted
	if u.ID == actor.ID {
		return nil, NewErrCannotDeleteYourself()
	}

	// Check if something went wrong
	// ex. The actor’s permission is not sufficient
	// ex. The user does not have a deletable status
	if false {
		return nil, errors.New("something went wrong")
	}

	return &DeletableUserID{UserID: u.ID}, nil
}
